### PR TITLE
Update dependencies (except timers-browserify)

### PR DESCRIPTION
**Pull request by clarfon**

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
Thanks for the PR! unfortunately the new stream related modules only support Node 6 and up, while browserify still works all the way back to Node 0.8.

The dev dependency updates look safe, and maybe path-is-absolute and is-buffer could work as well. would you mind downgrading the streams-related modules and seeing if CI agrees then?

**Comment by clarfon** [comment]
Ah, that makes sense!

I was mostly trying to help dedup the stream-related modules from my projects by offering dependency upgrades to projects, although if that's the case, I don't know if this will fit my use case. I'll try and take a look at messing with the other upgrades soonish though!

**Comment by clarfon** [comment]
Yeah, I'm going to just give up on this. I'd highly recommend breaking compatibility with 0.8 as it's been almost four years and hasn't been receiving security updates for a *long* time.

That said, I'm not in charge of this project, so, it's up to you to do what you think is right.

**Comment by goto-bus-stop** [comment]
Understood, sorry for the trouble!

**Pull request closed without merging**
